### ISSUE TITLE
v1.2 has no files

### ISSUE THREAD

**Issue by davemachado** [DarrienG/RockPaperSmash#1]
unzipping v1.2 results in no jars to run.

**Comment by davemachado** [comment]
<img width="203" alt="screen shot 2016-12-16 at 10 58 17 am" src="https://cloud.githubusercontent.com/assets/15134885/21268879/91b273aa-c37e-11e6-9b6c-9d8fc7c0d8f8.png">

**Comment by DarrienG** [comment]
FIXED :)))))))))

**Comment by DarrienG** [comment]
Please check the updated release.

**Comment by davemachado** [comment]
Closing issue, since it appears developer has updated the release zip.

**Comment by DarrienG** [comment]
I close these issues. I'm the developer.
